### PR TITLE
Refactor: using metapac

### PR DESCRIPTION
**Pull request by andelf**
This is a breaking change.

### CODE REVIEW

**Comment by Marcuss2** [comment]
So, if I understand correctly, you basically the some STM32 hals and rebuild them for the chip as the peripherals are register compatible.

Not sure if this is the best approach, but it will work for now.

**Comment by andelf** [comment]
> you basically the some STM32 hals and rebuild them for the chip as the peripherals are register compatible.

These YAML files are generated from https://github.com/ch32-rs/ch32-rs/tree/main/svd/fixed . They are using the toolset provided by stm32-data(https://github.com/embassy-rs/stm32-data).

**Comment by Marcuss2** [comment]
Ok, it should be fine then. The .modify(|w|) is due to new svd2rust?

**Review by Marcuss2 — APPROVED** [review]

**Comment by andelf** [comment]
> The .modify(|w|) is due to new svd2rust?

It's the difference between chiptool and svd2rust.
Maybe I can fix this.

**Pull request merged**
